import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ToDo Reminder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`antialiased sm:bg-[#f1f1f1] ` }
      >
        {children}
      </body>
    </html>
  );
}
